version:"3.8"
services:
  mongo:
    image:mongo:7
    ports:["27017:27017"]
  server:
    build:./server
    ports:["5000:5000"]
    environment:[MONGO_URI=mongodb://mongo:27017/merna]
  client:
    build:./client
    ports:["3000:3000"]
