const express=require('express'),mongoose=require('mongoose'),cors=require('cors');
const app=express();app.use(cors());app.use(express.json());
mongoose.connect(process.env.MONGO_URI||'mongodb://localhost:27017/kanban');
const Task=new mongoose.Schema({title:String,status:{type:String,enum:["To Do","In Progress","Done"],default:"To Do"},priority:{type:String,enum:["Low","Medium","High"],default:"Medium"},created:{type:Date,default:Date.now}});
const T=mongoose.model('Task',Task);
app.get('/api/tasks',async(req,res)=>{try{const{status,search}=req.query;let q={};if(status)q.status=status;if(search)q.title={$regex:search,$options:'i'};res.json(await T.find(q).sort({created:-1}))}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/tasks',async(req,res)=>{try{const t=new T({title:req.body.title,status:req.body.status||"To Do",priority:req.body.priority||"Medium"});await t.save();res.status(201).json(t)}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/tasks/:id',async(req,res)=>{try{const t=await T.findByIdAndUpdate(req.params.id,{title:req.body.title,status:req.body.status,priority:req.body.priority},{new:true});res.json(t)}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/tasks/:id',async(req,res)=>{try{await T.findByIdAndDelete(req.params.id);res.json({ok:1})}catch(e){res.status(400).json({error:e.message})}});
app.listen(process.env.PORT||5000,()=>console.log('Kanban server on',process.env.PORT||5000));
